name: Purge JsDelvir CDN Cache

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Purge Request
        id: purgeRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://purge.jsdelivr.net/gh/solflare-wallet/aptos-coinlist@master/aptos-coinlist.json"
      - name: Purge Response
        run: |
          echo ${{ steps.purgeRequest.outputs.response }}
          echo ${{ steps.purgeRequest.outputs.headers }}
